### ISSUE TITLE
Fails to build with glibc-2.23

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [xemul/criu#119]
make V=1

from git-master (same result with release 1.8)

> gcc -c -O2 -g -Wall -Werror -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -fno-strict-aliasing -iquote /tmp/criu/criu/include -iquote /tmp/criu/images -iquote /tmp/criu/criu/pie -iquote /tmp/criu/criu/arch/x86 -iquote /tmp/criu/criu/arch/x86/include -iquote /tmp/criu/ -I/usr/include/libnl3 -iquote arch/x86 -iquote /tmp/criu -iquote arch/x86/include -iquote /tmp/criu/criu/include arch/x86/crtools.c -o arch/x86/crtools.o
> In file included from arch/x86/crtools.c:14:0:
> /tmp/criu/criu/include/ptrace.h:47:0: error: "PTRACE_GETSIGMASK" redefined [-Werror]
>  #define PTRACE_GETSIGMASK 0x420a
>  ^
> In file included from /tmp/criu/criu/include/ptrace.h:5:0,
>                  from arch/x86/crtools.c:14:
> /usr/include/sys/ptrace.h:156:0: note: this is the location of the previous definition
>  #define PTRACE_GETSIGMASK PTRACE_GETSIGMASK
>  ^
> In file included from arch/x86/crtools.c:14:0:
> /tmp/criu/criu/include/ptrace.h:48:0: error: "PTRACE_SETSIGMASK" redefined [-Werror]
>  #define PTRACE_SETSIGMASK 0x420b
>  ^
> In file included from /tmp/criu/criu/include/ptrace.h:5:0,
>                  from arch/x86/crtools.c:14:
> /usr/include/sys/ptrace.h:159:0: note: this is the location of the previous definition
>  #define PTRACE_SETSIGMASK PTRACE_SETSIGMASK
>  ^
> cc1: all warnings being treated as errors
> /tmp/criu/scripts/nmk/scripts/rules.mk:53: recipe for target 'arch/x86/crtools.o' failed
> make[2]: *** [arch/x86/crtools.o] Error 1
> Makefile:110: recipe for target 'arch_lib' failed
> make[1]: *** [arch_lib] Error 2
> Makefile:120: recipe for target 'criu' failed
> make: *** [criu] Error 2
>

**Comment by avagin** [comment]
@MiRacLe-RPZ, could you try out this patch?
```
diff --git a/criu/include/ptrace.h b/criu/include/ptrace.h
index dfc5ecd..efea594 100644
--- a/criu/include/ptrace.h
+++ b/criu/include/ptrace.h
@@ -44,8 +44,10 @@ struct ptrace_peeksiginfo_args {
 # define PTRACE_SETREGSET      0x4205
 #endif
 
+#ifndef PTRACE_GETSIGMASK
 #define PTRACE_GETSIGMASK      0x420a
 #define PTRACE_SETSIGMASK      0x420b
+#endif
 
 #ifndef PTRACE_SECCOMP_GET_FILTER
 #define PTRACE_SECCOMP_GET_FILTER      0x420c
```

**Comment by MiRacLe-RPZ** [comment]
@avagin, yes this patch fix issue
